# Generated by Django 6.0.6 on 2026-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('type_actif', models.CharField(choices=[('SERVEUR', 'Serveur'), ('PC', 'PC'), ('ROUTEUR', 'Routeur'), ('SWITCH', 'Switch'), ('APPLICATION', 'Application')], max_length=20)),
                ('criticite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Elevé'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('systeme', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
