# Generated by Django 6.0.6 on 2026-06-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPLIQUEE', 'Appliquée'), ('IGNOREE', 'Ignorée')], default='EN_ATTENTE', max_length=15)),
                ('score_risque', models.FloatField(default=0.0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='incidents.incident')),
            ],
        ),
    ]
