# Generated by Django 6.0.6 on 2026-06-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_rapport', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], max_length=10)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='utilisateurs.utilisateur')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='incidents.incident')),
            ],
        ),
    ]
