# Generated by Django 6.0.6 on 2026-06-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('BAS', 'Bas'), ('MOYEN', 'Moyen'), ('HAUT', 'Haut'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('description', models.TextField()),
                ('source', models.CharField(default='Suricata', max_length=50)),
                ('est_lue', models.BooleanField(default=False)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='actifs.actif')),
            ],
        ),
    ]
