# Generated by Django 6.0.6 on 2026-06-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('score_cvss', models.FloatField()),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Elevé'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('correctif', models.TextField(blank=True)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilites', to='actifs.actif')),
            ],
        ),
    ]
